POST http://localhost:8080/bid HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "user_id": "365fb343-e3d7-48b7-bc35-fa1a4b6a9a94",
    "auction_id": "7b985cdb-82b4-4169-b2ed-6ac52eb1f84c",
    "amount": 10.5
}