POST http://localhost:8080/bid HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "user_id": "365fb343-e3d7-48b7-bc35-fa1a4b6a9a94",
    "auction_id": "7522218c-ab3c-4f76-8508-4258b359221a",
    "amount": 90
}