### Requisição 1: GET para listar todos leitões
GET http://localhost:8080/auction?status=0 HTTP/1.1

### Requisição 2: GET para listar leilão pelo UUID
GET http://localhost:8080/auction/7522218c-ab3c-4f76-8508-4258b359221a HTTP/1.1

### Requisição 3: GET para listar leitão vencedor
GET http://localhost:8080/auction/winner/7522218c-ab3c-4f76-8508-4258b359221a HTTP/1.1

### Requisição 4: GET para listar oferta
GET http://localhost:8080/bid/7522218c-ab3c-4f76-8508-4258b359221a HTTP/1.1

### Requisição 5: GET para listar usuário pelo UUID
GET http://localhost:8080/user/365fb343-e3d7-48b7-bc35-fa1a4b6a9a94 HTTP/1.1
